<a href="https://colab.research.google.com/github/waqarmm/AI-Labs/blob/master/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import scipy

lr=pd.read_csv('./Logistic_Regression_dataset.csv')

lr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   length  100 non-null    float64
 1   width   100 non-null    float64
 2   Type    100 non-null    int64  
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [13]:
def readData(file_name):
  data=pd.read_csv(file_name)
  X=data[['length','width']]
  y=data['Type']
  X=np.concatenate((np.ones((X.shape[0],1)),X),axis=1)
  return X,y



In [16]:
X,y=readData('./Logistic_Regression_dataset.csv')

# print(X)
# print(y)

In [23]:
def LogisticRegressionModel(X_train,X_test,y_train,y_test):
  reg=LogisticRegression(random_state=0).fit(X_train,y_train)
  train_Acc=reg.score(X_train,y_train)
  test_Acc=reg.score(X_test,y_test)
  y_train_pred=reg.predict(X_train)
  y_test_pred=reg.predict(X_test)
  train_error=metrics.mean_absolute_error(y_train,y_train_pred)/1000
  test_error=metrics.mean_absolute_error(y_test,y_test_pred)/1000
  coef=reg.coef_
  return test_Acc,train_Acc,train_error,test_error,coef

In [36]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
test_Acc,train_Acc,train_error,test_error,coef=LogisticRegressionModel(X_train,X_test,y_train,y_test)

print("TEST ACCURACCY",test_Acc,"TRAIN ACCURACCY",train_Acc,"train_error",train_error)

#plt.imshow(X_train,y_train)
print(X_train[:500000000000])
print(y_test[:10000000000000])


TEST ACCURACCY 1.0 TRAIN ACCURACCY 1.0 train_error 0.0
[[1.  6.1 2.9]
 [1.  5.4 3.4]
 [1.  6.  3.4]
 [1.  5.6 2.9]
 [1.  6.1 2.8]
 [1.  4.5 2.3]
 [1.  6.6 2.9]
 [1.  6.9 3.1]
 [1.  5.2 2.7]
 [1.  4.9 3.1]
 [1.  4.8 3.4]
 [1.  4.8 3. ]
 [1.  6.4 3.2]
 [1.  5.1 3.7]
 [1.  4.6 3.2]
 [1.  4.3 3. ]
 [1.  5.1 3.5]
 [1.  5.7 2.8]
 [1.  5.1 3.8]
 [1.  6.3 2.3]
 [1.  4.8 3. ]
 [1.  5.  2. ]
 [1.  5.5 4.2]
 [1.  5.8 2.6]
 [1.  6.  2.2]
 [1.  5.5 3.5]
 [1.  5.9 3.2]
 [1.  4.4 3.2]
 [1.  5.5 2.4]
 [1.  7.  3.2]
 [1.  5.4 3.7]
 [1.  4.6 3.1]
 [1.  4.4 3. ]
 [1.  5.8 2.7]
 [1.  5.  3.4]
 [1.  5.8 2.7]
 [1.  5.  3.6]
 [1.  6.1 3. ]
 [1.  4.6 3.6]
 [1.  6.7 3.1]
 [1.  5.2 3.4]
 [1.  6.  2.9]
 [1.  6.7 3.1]
 [1.  4.7 3.2]
 [1.  5.1 3.3]
 [1.  6.3 3.3]
 [1.  6.3 2.5]
 [1.  5.  2.3]
 [1.  4.9 2.4]
 [1.  6.2 2.2]
 [1.  5.7 4.4]
 [1.  5.  3.4]
 [1.  5.4 3.4]
 [1.  5.7 2.9]
 [1.  5.6 3. ]
 [1.  4.8 3.1]
 [1.  5.2 4.1]
 [1.  5.1 3.8]
 [1.  4.9 3.1]
 [1.  6.1 2.8]
 [1.  5.6 2.7]
 [1.  5.1 3.8]
 [1.  6.6 3. ]
